import {
  BadgeDollarSign,
  BarChart3,
  CalendarCheck,
  Car,
  ClipboardList,
  LayoutDashboard,
  ReceiptText,
  ShieldCheck,
  Users,
  UserCog,
  Wrench,
} from "lucide-react"

import type { AdminModule, SidebarGroup } from "./types"

export const dashboardCards = [
  {
    color:
      "border-l-blue-500 bg-blue-50 text-blue-700 dark:bg-blue-950/30 dark:text-blue-200",
    icon: Car,
    label: "Total Vehicles",
    value: "0",
  },
  {
    color:
      "border-l-emerald-500 bg-emerald-50 text-emerald-700 dark:bg-emerald-950/30 dark:text-emerald-200",
    icon: Car,
    label: "Available Vehicles",
    value: "0",
  },
  {
    color:
      "border-l-amber-500 bg-amber-50 text-amber-700 dark:bg-amber-950/30 dark:text-amber-200",
    icon: CalendarCheck,
    label: "Reserved Vehicles",
    value: "0",
  },
  {
    color:
      "border-l-rose-500 bg-rose-50 text-rose-700 dark:bg-rose-950/30 dark:text-rose-200",
    icon: BadgeDollarSign,
    label: "Sold Vehicles",
    value: "0",
  },
  {
    color:
      "border-l-cyan-500 bg-cyan-50 text-cyan-700 dark:bg-cyan-950/30 dark:text-cyan-200",
    icon: Users,
    label: "Active Customers",
    value: "0",
  },
  {
    color:
      "border-l-green-500 bg-green-50 text-green-700 dark:bg-green-950/30 dark:text-green-200",
    icon: ReceiptText,
    label: "Monthly Sales",
    value: "0",
  },
  {
    color:
      "border-l-orange-500 bg-orange-50 text-orange-700 dark:bg-orange-950/30 dark:text-orange-200",
    icon: CalendarCheck,
    label: "Pending Reservations",
    value: "0",
  },
  {
    color:
      "border-l-violet-500 bg-violet-50 text-violet-700 dark:bg-violet-950/30 dark:text-violet-200",
    icon: Wrench,
    label: "Maintenance Requests",
    value: "0",
  },
]

export const statIconStyles = [
  "bg-blue-50 text-blue-700 dark:bg-blue-950/30 dark:text-blue-200",
  "bg-emerald-50 text-emerald-700 dark:bg-emerald-950/30 dark:text-emerald-200",
  "bg-amber-50 text-amber-700 dark:bg-amber-950/30 dark:text-amber-200",
]

export const monthlySalesData = [
  { label: "Jan", value: 0 },
  { label: "Feb", value: 0 },
  { label: "Mar", value: 0 },
  { label: "Apr", value: 0 },
  { label: "May", value: 0 },
  { label: "Jun", value: 0 },
]

export const vehicleStatusData = [
  { color: "#2563eb", label: "Available", value: 0 },
  { color: "#f59e0b", label: "Reserved", value: 0 },
  { color: "#ef4444", label: "Sold", value: 0 },
]

export const operationsRadarData = [
  { label: "Inventory", value: 0 },
  { label: "Sales", value: 0 },
  { label: "Reservations", value: 0 },
  { label: "Maintenance", value: 0 },
  { label: "Customers", value: 0 },
]

export const adminModules: AdminModule[] = [
  {
    id: "users",
    actionSet: "user-access",
    route: "admin/user-management",
    title: "User Management",
    navLabel: "User Management",
    description:
      "Create, update, deactivate, and assign roles and permissions to system users.",
    icon: ShieldCheck,
    primaryAction: "Create User",
    stats: [
      { label: "Active Users", value: "0" },
      { label: "Deactivated", value: "0" },
      { label: "Roles", value: "0" },
    ],
    records: [],
  },
  {
    id: "roles",
    actionSet: "role-access",
    route: "admin/role-management",
    title: "Role Management",
    navLabel: "Role Management",
    description:
      "Configure system roles, access permissions, and module-level authorization for each user type.",
    icon: ShieldCheck,
    primaryAction: "Create Role",
    stats: [
      { label: "System Roles", value: "0" },
      { label: "Permission Groups", value: "0" },
      { label: "Restricted Modules", value: "0" },
    ],
    records: [],
  },
  {
    id: "staff",
    actionSet: "staff",
    route: "admin/staff",
    title: "Manage Staff",
    navLabel: "Staff",
    description:
      "Maintain staff information, monitor staff activities, and manage employee records.",
    icon: UserCog,
    primaryAction: "Add Staff",
    stats: [
      { label: "Employees", value: "0" },
      { label: "On Duty", value: "0" },
      { label: "Activities Today", value: "0" },
    ],
    records: [],
  },
  {
    id: "vehicles",
    actionSet: "vehicle-inventory",
    route: "admin/vehicles",
    title: "Manage Vehicles",
    navLabel: "Vehicles",
    description:
      "Manage vehicle inventory and stock status including brand, model, year, color, engine/chassis numbers, plate number, mileage, pricing, photos, location, and availability.",
    icon: Car,
    primaryAction: "Add Vehicle",
    stats: [
      { label: "Inventory Units", value: "0" },
      { label: "Available", value: "0" },
      { label: "For Repair", value: "0" },
    ],
    records: [],
  },
  {
    id: "job-orders",
    actionSet: "admin-job-orders",
    route: "admin/job-orders-maintenance",
    title: "Manage Job Orders & Maintenance",
    navLabel: "Job Orders",
    description:
      "Create job orders, assign mechanics or staff, track preparation progress, record labor and parts cost, upload before/after photos, and print job order history.",
    icon: Wrench,
    primaryAction: "Create Job Order",
    stats: [
      { label: "Open Job Orders", value: "0" },
      { label: "Waiting Parts", value: "0" },
      { label: "Completed Today", value: "0" },
    ],
    columns: [
      "JO No.",
      "Vehicle",
      "Status",
    ],
    recordsTitle: "Job Order Lists",
    recordsDescription:
      "Manage vehicle preparation, repair, detailing, and maintenance before releasing or selling the unit.",
    defaultStatusFilter: "All Records",
    statusNavigation: [
      { label: "All Records" },
      { label: "Active Work", statuses: ["Pending", "In Progress", "Waiting for Parts"] },
      { label: "Pending", statuses: ["Pending"] },
      { label: "In Progress", statuses: ["In Progress"] },
      { label: "Waiting Parts", statuses: ["Waiting for Parts"] },
      { label: "Completed", statuses: ["Completed"] },
      { label: "Cancelled", statuses: ["Cancelled"] },
    ],
    records: [],
  },
  {
    id: "customers",
    actionSet: "customers",
    route: "admin/customers",
    title: "Manage Customers",
    navLabel: "Customers",
    description:
      "View and maintain customer records, transaction history, and customer information.",
    icon: Users,
    primaryAction: "Add Customer",
    stats: [
      { label: "Active Customers", value: "0" },
      { label: "New This Month", value: "0" },
      { label: "With Balance", value: "0" },
    ],
    records: [],
  },
  {
    id: "sales",
    actionSet: "sales-payments",
    route: "admin/sales-payments",
    title: "Manage Sales & Payments",
    navLabel: "Sales & Payments",
    description:
      "Create sales transactions, convert reservations to sales, generate invoices and receipts, monitor cash and financing payments, and track balances.",
    icon: BadgeDollarSign,
    primaryAction: "Create Sales Transaction",
    stats: [
      { label: "Monthly Sales", value: "PHP 2.4M" },
      { label: "Payments Today", value: "PHP 185K" },
      { label: "Outstanding", value: "PHP 890K" },
    ],
    columns: [
      "Reference",
      "Customer",
      "Vehicle",
      "Method",
      "Selling Price",
      "Discount",
      "Down Payment",
      "Paid",
      "Balance",
      "Invoice",
      "Receipt",
      "Proof",
      "Schedule",
      "Release",
      "Status",
    ],
    recordsTitle: "Sales & Payment History",
    recordsDescription:
      "Process full cash payments, financing down payments, monthly collections, receipts, vehicle release, and outstanding balances.",
    records: [
      {
        Reference: "SALE-2026-001",
        Customer: "Maria Santos",
        Vehicle: "Toyota Vios 2021 E",
        Method: "Cash",
        "Selling Price": "PHP 750,000",
        Discount: "PHP 10,000",
        "Down Payment": "PHP 0",
        Paid: "PHP 740,000",
        Balance: "PHP 0",
        Invoice: "INV-2026-001",
        Receipt: "OR-0001",
        Proof: "Uploaded",
        Schedule: "Full payment",
        Release: "Released",
        Status: "Completed",
      },
      {
        Reference: "SALE-2026-002",
        Customer: "John Reyes",
        Vehicle: "Ford Ranger 2020 XLS",
        Method: "Financing",
        "Selling Price": "PHP 980,000",
        Discount: "PHP 0",
        "Down Payment": "PHP 180,000",
        Paid: "PHP 210,000",
        Balance: "PHP 770,000",
        Invoice: "INV-2026-002",
        Receipt: "OR-0002",
        Proof: "Uploaded",
        Schedule: "36 monthly payments",
        Release: "For Release",
        Status: "Processing",
      },
      {
        Reference: "SALE-2026-003",
        Customer: "Angela Lim",
        Vehicle: "Honda BR-V 2022 S",
        Method: "Financing",
        "Selling Price": "PHP 890,000",
        Discount: "PHP 15,000",
        "Down Payment": "PHP 150,000",
        Paid: "PHP 165,000",
        Balance: "PHP 710,000",
        Invoice: "INV-2026-003",
        Receipt: "OR-0003",
        Proof: "Pending",
        Schedule: "Late payment flagged",
        Release: "Hold",
        Status: "Partial",
      },
    ],
  },
  {
    id: "reservations",
    actionSet: "reservations",
    route: "admin/reservations",
    title: "Manage Reservations",
    navLabel: "Reservations",
    description:
      "Create reservations, search available vehicles, record fees and payment method, upload and verify documents, update reservation status, and print forms.",
    icon: CalendarCheck,
    primaryAction: "Create Reservation",
    stats: [
      { label: "Active Reservations", value: "8" },
      { label: "Pending", value: "3" },
      { label: "Expiring Soon", value: "2" },
    ],
    columns: [
      "Reservation",
      "Customer",
      "Vehicle",
      "Reservation Fee",
      "Payment Method",
      "Expiry Date",
      "Documents",
      "Requirements",
      "History",
      "Status",
    ],
    recordsTitle: "Reservation History",
    recordsDescription:
      "Reserve available vehicles before purchase and track documents, expiry, cancellation, and conversion to sale.",
    defaultStatusFilter: "Active Reservations",
    statusNavigation: [
      { label: "Active Reservations", statuses: ["Pending", "Confirmed"] },
      { label: "Pending", statuses: ["Pending"] },
      { label: "Confirmed", statuses: ["Confirmed"] },
      { label: "Expired", statuses: ["Expired"] },
      { label: "Cancelled", statuses: ["Cancelled"] },
      { label: "Converted", statuses: ["Converted to Sale"] },
      { label: "All History" },
    ],
    records: [
      {
        Reservation: "RES-2026-001",
        Customer: "Kevin Uy",
        Vehicle: "Toyota Fortuner 2021 G",
        "Reservation Fee": "PHP 20,000",
        "Payment Method": "Financing",
        "Expiry Date": "Jul 05, 2026",
        Documents: "Valid ID, Proof of Income",
        Requirements: "For verification",
        History: "Created Jun 25, 2026",
        Status: "Pending",
      },
      {
        Reservation: "RES-2026-002",
        Customer: "Liza Gomez",
        Vehicle: "Mitsubishi Mirage 2022 GLX",
        "Reservation Fee": "PHP 15,000",
        "Payment Method": "Cash",
        "Expiry Date": "Jul 01, 2026",
        Documents: "Valid ID, Proof of Payment",
        Requirements: "Verified",
        History: "Confirmed Jun 24, 2026",
        Status: "Confirmed",
      },
      {
        Reservation: "RES-2026-003",
        Customer: "Patrick Tan",
        Vehicle: "Nissan Terra 2020 VL",
        "Reservation Fee": "PHP 10,000",
        "Payment Method": "Financing",
        "Expiry Date": "Jun 22, 2026",
        Documents: "Application Form",
        Requirements: "Incomplete",
        History: "Expired automatically",
        Status: "Expired",
      },
      {
        Reservation: "RES-2026-004",
        Customer: "Rhea Cruz",
        Vehicle: "Honda Civic 2019 RS",
        "Reservation Fee": "PHP 25,000",
        "Payment Method": "Cash",
        "Expiry Date": "Jun 29, 2026",
        Documents: "Valid ID, Proof of Payment",
        Requirements: "Converted",
        History: "Converted to SALE-2026-004",
        Status: "Converted to Sale",
      },
      {
        Reservation: "RES-2026-005",
        Customer: "Noel Bautista",
        Vehicle: "Ford Territory 2021 Titanium",
        "Reservation Fee": "PHP 12,000",
        "Payment Method": "Cash",
        "Expiry Date": "Jun 27, 2026",
        Documents: "Valid ID",
        Requirements: "Cancelled by customer",
        History: "Cancelled Jun 26, 2026",
        Status: "Cancelled",
      },
    ],
  },
  {
    id: "requirements",
    actionSet: "requirements",
    route: "admin/requirements",
    title: "Requirements",
    navLabel: "Requirements",
    description:
      "Manage customer submission requirements for cash basis, financing basis, document proof, and verification records.",
    icon: ClipboardList,
    primaryAction: "Add Requirement",
    stats: [
      { label: "Requirement Types", value: "3" },
      { label: "Required Documents", value: "0" },
      { label: "For Verification", value: "0" },
    ],
    recordsTitle: "Requirements List",
    recordsDescription:
      "Required IDs, payment proofs, and financing documents for online customer submission.",
    records: [
      {
        Requirement: "Cash Basis Verification",
        Category: "Cash Basis",
        "Required From": "Customer",
        Documents: "1 valid verification ID",
        Status: "Active",
      },
      {
        Requirement: "Financing Documents",
        Category: "Financing Basis",
        "Required From": "Customer",
        Documents: "Application documents, valid ID, proof of income, supporting financing records",
        Status: "Active",
      },
      {
        Requirement: "Online Proof Submission",
        Category: "Document Upload",
        "Required From": "Customer",
        Documents: "Proof of payment, IDs, financing documents, and other required files",
        Status: "Active",
      },
    ],
  },
  {
    id: "reports",
    actionSet: "reports",
    route: "admin/reports",
    title: "Generate Reports",
    navLabel: "Reports",
    description:
      "Generate sales, reservation, job order, payment, vehicle, and customer reports for monitoring business operations.",
    icon: BarChart3,
    primaryAction: "Generate Report",
    stats: [
      { label: "Report Types", value: "25" },
      { label: "Generated Today", value: "5" },
      { label: "Scheduled", value: "4" },
    ],
    columns: ["Report", "Category", "Coverage", "Included Data", "Generated By", "Last Generated", "Status"],
    recordsTitle: "Report Center",
    recordsDescription:
      "Generate daily, weekly, monthly, annual, inventory, reservation, job order, payment, customer, and collection reports.",
    records: [
      {
        Report: "Daily Sales Report",
        Category: "Sales Reports",
        Coverage: "Today",
        "Included Data": "Sales invoice, selling price, discount, total amount",
        "Generated By": "Admin",
        "Last Generated": "Jun 26, 2026 8:00 AM",
        Status: "Ready",
      },
      {
        Report: "Weekly Sales Report",
        Category: "Sales Reports",
        Coverage: "This Week",
        "Included Data": "Sales transactions, discounts, totals, released units",
        "Generated By": "Admin",
        "Last Generated": "Jun 24, 2026 6:00 PM",
        Status: "Ready",
      },
      {
        Report: "Monthly Sales Report",
        Category: "Sales Reports",
        Coverage: "June 2026",
        "Included Data": "Monthly sales totals, paid amounts, balances, invoices",
        "Generated By": "Admin",
        "Last Generated": "Jun 26, 2026 9:00 AM",
        Status: "Ready",
      },
      {
        Report: "Annual Sales Report",
        Category: "Sales Reports",
        Coverage: "2026",
        "Included Data": "Annual sales trend, vehicle sold count, revenue totals",
        "Generated By": "Admin",
        "Last Generated": "Jun 20, 2026 5:10 PM",
        Status: "Scheduled",
      },
      {
        Report: "Sales by Vehicle",
        Category: "Sales Reports",
        Coverage: "All Sold Units",
        "Included Data": "Vehicle, selling price, customer, sale date, payment method",
        "Generated By": "Sales",
        "Last Generated": "Jun 25, 2026 3:15 PM",
        Status: "Ready",
      },
      {
        Report: "Active Reservations",
        Category: "Reservation Reports",
        Coverage: "Current Month",
        "Included Data": "Pending, confirmed, expired, cancelled, converted reservations",
        "Generated By": "Secretary",
        "Last Generated": "Jun 25, 2026 4:30 PM",
        Status: "Ready",
      },
      {
        Report: "Expired Reservations",
        Category: "Reservation Reports",
        Coverage: "Current Month",
        "Included Data": "Expired reservations, expiry dates, customers, vehicles",
        "Generated By": "Secretary",
        "Last Generated": "Jun 23, 2026 1:40 PM",
        Status: "Ready",
      },
      {
        Report: "Cancelled Reservations",
        Category: "Reservation Reports",
        Coverage: "Current Month",
        "Included Data": "Cancelled reservations, reasons, released vehicles",
        "Generated By": "Secretary",
        "Last Generated": "Jun 22, 2026 11:20 AM",
        Status: "Ready",
      },
      {
        Report: "Reservation Summary",
        Category: "Reservation Reports",
        Coverage: "June 2026",
        "Included Data": "Pending, confirmed, expired, cancelled, converted reservations",
        "Generated By": "Secretary",
        "Last Generated": "Jun 26, 2026 8:45 AM",
        Status: "Ready",
      },
      {
        Report: "Pending Job Orders",
        Category: "Job Order Reports",
        Coverage: "Open Work",
        "Included Data": "Priority, assigned staff, target completion, labor cost, parts used",
        "Generated By": "Operations",
        "Last Generated": "Jun 26, 2026 9:15 AM",
        Status: "Scheduled",
      },
      {
        Report: "Completed Job Orders",
        Category: "Job Order Reports",
        Coverage: "Completed Work",
        "Included Data": "Completed date, labor cost, parts used, before/after photos",
        "Generated By": "Operations",
        "Last Generated": "Jun 25, 2026 6:30 PM",
        Status: "Ready",
      },
      {
        Report: "Mechanic Performance",
        Category: "Job Order Reports",
        Coverage: "June 2026",
        "Included Data": "Assigned jobs, completion rate, average turnaround, remarks",
        "Generated By": "Operations",
        "Last Generated": "Jun 24, 2026 7:10 PM",
        Status: "Ready",
      },
      {
        Report: "Vehicle Service History",
        Category: "Job Order Reports",
        Coverage: "All Vehicles",
        "Included Data": "Service type, parts, labor, photos, progress notes",
        "Generated By": "Operations",
        "Last Generated": "Jun 26, 2026 10:30 AM",
        Status: "Ready",
      },
      {
        Report: "Cash Payments",
        Category: "Payment Reports",
        Coverage: "June 2026",
        "Included Data": "Full payments, official receipts, proof of payment",
        "Generated By": "Cashier",
        "Last Generated": "Jun 26, 2026 9:30 AM",
        Status: "Ready",
      },
      {
        Report: "Financing Payments",
        Category: "Payment Reports",
        Coverage: "June 2026",
        "Included Data": "Down payments, monthly payments, payment schedules",
        "Generated By": "Cashier",
        "Last Generated": "Jun 25, 2026 4:00 PM",
        Status: "Ready",
      },
      {
        Report: "Outstanding Balances",
        Category: "Payment Reports",
        Coverage: "All Accounts",
        "Included Data": "Cash, financing, monthly payments, late payment, remaining balance",
        "Generated By": "Cashier",
        "Last Generated": "Jun 24, 2026 2:20 PM",
        Status: "Ready",
      },
      {
        Report: "Fully Paid Customers",
        Category: "Payment Reports",
        Coverage: "All Accounts",
        "Included Data": "Fully paid sales, receipt numbers, release status",
        "Generated By": "Cashier",
        "Last Generated": "Jun 25, 2026 9:25 AM",
        Status: "Ready",
      },
      {
        Report: "Collection Report",
        Category: "Payment Reports",
        Coverage: "Today",
        "Included Data": "Cash collections, financing collections, late payments",
        "Generated By": "Cashier",
        "Last Generated": "Jun 26, 2026 11:00 AM",
        Status: "Ready",
      },
      {
        Report: "Available Vehicles",
        Category: "Vehicle Reports",
        Coverage: "Current Inventory",
        "Included Data": "Available units, selling price, reservation fee, location",
        "Generated By": "Admin",
        "Last Generated": "Jun 26, 2026 10:05 AM",
        Status: "Ready",
      },
      {
        Report: "Reserved Vehicles",
        Category: "Vehicle Reports",
        Coverage: "Current Inventory",
        "Included Data": "Reserved units, customer, reservation expiry, fee",
        "Generated By": "Admin",
        "Last Generated": "Jun 26, 2026 10:08 AM",
        Status: "Ready",
      },
      {
        Report: "Sold Vehicles",
        Category: "Vehicle Reports",
        Coverage: "Sold Units",
        "Included Data": "Sold vehicles, customer, invoice, release status",
        "Generated By": "Admin",
        "Last Generated": "Jun 26, 2026 10:09 AM",
        Status: "Ready",
      },
      {
        Report: "Vehicle Inventory",
        Category: "Vehicle Reports",
        Coverage: "All Units",
        "Included Data": "Available, reserved, sold, inventory details, service history",
        "Generated By": "Admin",
        "Last Generated": "Jun 26, 2026 10:10 AM",
        Status: "Ready",
      },
      {
        Report: "Customer List",
        Category: "Customer Reports",
        Coverage: "All Customers",
        "Included Data": "Customer name, contact, email, account status",
        "Generated By": "Admin",
        "Last Generated": "Jun 25, 2026 12:15 PM",
        Status: "Ready",
      },
      {
        Report: "Purchase History",
        Category: "Customer Reports",
        Coverage: "All Customers",
        "Included Data": "Purchased vehicles, sale date, payment method, receipt",
        "Generated By": "Admin",
        "Last Generated": "Jun 24, 2026 4:50 PM",
        Status: "Ready",
      },
      {
        Report: "Customer Transaction History",
        Category: "Customer Reports",
        Coverage: "All Customers",
        "Included Data": "Customer list, purchase history, reservations, payments",
        "Generated By": "Admin",
        "Last Generated": "Jun 23, 2026 5:45 PM",
        Status: "Ready",
      },
    ],
  },
]

export const adminModuleMap = Object.fromEntries(
  adminModules.map((module) => [module.id, module]),
) as Record<string, AdminModule>

export const sidebarGroups: SidebarGroup[] = [
  {
    label: "Main",
    items: [
      {
        icon: LayoutDashboard,
        id: "overview",
        route: "admin/dashboard",
        title: "Dashboard",
      },
    ],
  },
  {
    label: "Operations",
    items: adminModules
      .filter(
        (module) =>
          module.id !== "users" &&
          module.id !== "roles",
      )
      .map(({ icon, id, navLabel, route }) => ({
        icon,
        id,
        route,
        title: navLabel,
      })),
  },
  {
    label: "Access Control",
    items: adminModules
      .filter((module) => module.id === "users" || module.id === "roles")
      .map(({ icon, id, navLabel, route }) => ({
        icon,
        id,
        route,
        title: navLabel,
      })),
  },
]
